name: Identify Deleted Files

on:
  push:
    branches:
      - test

jobs:
  identify-deleted-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v2
        with:
          ref: test

      - name: Identify deleted files
        run: |
          # get the SHA of the previous commit
          PREVIOUS_SHA=$(git rev-parse HEAD^)
          # get a list of deleted files
          DELETED_FILES=$(git diff --name-only HEAD^ HEAD --diff-filter=D)
          # print the list of deleted files
          echo "Deleted files: $DELETED_FILES"
